/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistema_carcerario.view;

import DAL.PrisioneiroDao;
import com.mycompany.sistema_carcerario.model.Prisioneiro;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author m138824
 */
public class BuscarPanel extends javax.swing.JPanel {
    final MainFrame parent;
    
    private final PrisioneiroDao prisioneiroDao = new PrisioneiroDao();
            
    /**
     * Creates new form BuscarPanel
     */
    public BuscarPanel(MainFrame parent) {
        initComponents();
        this.parent = parent;
        
        populateTablePrisioneiros("");
        
        // Quando clicar valor na tabela irá ir para o prisioneiro na tela de atendimento
        tabela_prisioneiros.addMouseListener(new MouseAdapter() {
        @Override 
        public void mouseClicked(MouseEvent e) {
            int row = tabela_prisioneiros.getSelectedRow();
            if (row >= 0) {
                int idPrisioneiro = (int) tabela_prisioneiros.getValueAt(row, 0);
                parent.showAtendimentoPanel(idPrisioneiro);
            }
        }
    });
    }

    
    private void populateTablePrisioneiros(String filter) {
        List<Prisioneiro> prisioneiroList = prisioneiroDao.listarPrisioneiros(filter);
        
        String[] headers = {"ID", "Nome", "CPF", "Idade", "Nome da Mãe"};
        DefaultTableModel model = new DefaultTableModel(headers, 0);

        for (Prisioneiro p : prisioneiroList) {
            Object[] row = {
                p.getId(),
                p.getNome(),
                p.getCpf(),
                p.calcularIdade(), 
                p.getNomeMae()
            };
            model.addRow(row);
        }

        tabela_prisioneiros.setModel(model);

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_prisioneiros = new javax.swing.JTable();
        lb_nome = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();

        tabela_prisioneiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Idade", "Title 5"
            }
        ));
        jScrollPane3.setViewportView(tabela_prisioneiros);

        lb_nome.setText("Nome:");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_cadastrar)
                    .addComponent(lb_nome))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        parent.showAtendimentoPanelParaNovo();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String filter =  tf_nome.getText();
        
        populateTablePrisioneiros(filter);
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JTable tabela_prisioneiros;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables
}
